import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:objectbox/objectbox.dart';
import '../objectbox.g.dart'; // generated by objectbox_generator; provides openStore()

/// Opens the ObjectBox store. Call once in main() before runApp.
Future<Store> openRiskStore() async {
  return openStore(directory: 'obx-risk');
}

/// Provider that holds the ObjectBox store.
/// Override with actual store in main.dart via ProviderScope.overrides.
final storeProvider = Provider<Store>(
  (ref) => throw UnimplementedError('storeProvider must be overridden at startup'),
);
